### ISSUE TITLE
shadow without lastSyncDate that isn't in error state

### ISSUE THREAD

**Issue by isaac** [jessegrosjean/DropboxSync#10] opened 2011-04-26 22:27 UTC
Hi Guys,

Thanks for open sourcing DropboxSync, it has been great to use so far, except for a few issues.  This is the first one:

I am using DropboxSync in an iPhone app to sync one directory of text files and one of our beta testers keeps on getting a crash with the error: "NSInternalInconsistencyException: shadow without lastSyncDate that isn't in error state".

This error seems to be coming from this NSAsset here: https://github.com/jessegrosjean/DropboxSync/blob/master/Source/FolderSyncPathOperation.m#L145

I can't figure out why this is happening and the only way I reproduce this locally is edit the PathMetadata.sqlite database manually and set one of the files lastSyncDate to NULL.

Do you have any idea why this might be happening and how I could work around this issue in my app?

Cheers,
Isaac

**Comment by jessegrosjean** [comment] 2011-05-17 17:59
I'm sorry for my very late response here. I don't know what's causing this. I do see a similar bug report from one of my users (6 months back), but nothing since then. If your user can still reproduce the problem maybe get them to do a clean reinstall and then add some tracing code to try to figure out the cause?

**Comment by isaac** [comment] 2011-05-17 23:18
Hi Jesse,

Thanks for the response.  I ended up removing DropboxSync from my project and using the Dropbox SDK directly.  Instead of true sync I have adopted more of a backup and restore approach which seems to be more practical for now.

One change that would have made DropboxSync more useful for me is some sort of callback when there was a conflict.  So instead of creating "...(conflicted copy)" files I could choose to take another approach.

Anyway, you can go ahead and close this issue as I suspect I will never figure out why this was happening.

Thanks again for open-sourcing this code, I hope I'll get a chance to use it again sometime.

Cheers,
Isaac

**Comment by jessegrosjean** [comment] 2011-05-18 12:48
Ok, thanks, I'll close it out.

**Closed as completed by jessegrosjean** 2011-05-18 12:48 UTC
